version: '3.7'
services:
  elasticsearch:
    image: docker.io/library/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.io/library/kibana:8.14.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  logstash:
    image: docker.io/library/logstash:8.14.3
    volumes:
      - ./pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "9600:9600"

volumes:
  es_data:
